kind: PersistentVolume
apiVersion: v1
metadata:
 name: mongodb-pv
 labels:
  type: local
spec:
 storageClassName: {{ .Values.mongopv.storageclassname }}
 capacity:
  storage: 1Gi
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: {{ .Values.mongopv.hostpath }}
