apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mongodb-claim0
  name: mongodb-claim0
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.mongopv.storageclassname }}
  resources:
    requests:
      storage: 1Gi

